version: "3"
 
services:
  php:
    container_name: php_board
    build:
      context: ./php
    ports:
      - 8080:80
    volumes:
      - ./htdocs:/var/www/html
    restart: always
  db:
    container_name: mysql_board
    image: mysql:latest
    volumes:
      - ./mysqlvol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: board_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

volumes:
  mysqlvol: